FSWDFinalProject.UI.MVC/Controllers/OpenPositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FSWDFinalProject.DATA.EF;
using Microsoft.AspNet.Identity;

namespace FSWDFinalProject.UI.MVC.Controllers
{
    public class OpenPositionsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: OpenPositions
        public ActionResult Index()
        {
            var openPositions = db.OpenPositions.Include(o => o.Location).Include(o => o.Position);
            return View(openPositions.ToList());
        }

        // GET: OpenPositions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            return View(openPosition);
        }

        // GET: OpenPositions/Create
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Create()
        {
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "StoreNumber");
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title");
            return View();
        }

        // POST: OpenPositions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin, Manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OpenPositionId,PositionId,LocationId")] OpenPosition openPosition)
        {
            if (ModelState.IsValid)
            {
                db.OpenPositions.Add(openPosition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "StoreNumber", openPosition.LocationId);
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }

        // GET: OpenPositions/Edit/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "StoreNumber", openPosition.LocationId);
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }

        // POST: OpenPositions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin, Manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OpenPositionId,PositionId,LocationId")] OpenPosition openPosition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(openPosition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "StoreNumber", openPosition.LocationId);
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }

        // GET: OpenPositions/Delete/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            return View(openPosition);
        }

        // POST: OpenPositions/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin, Manager")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OpenPosition openPosition = db.OpenPositions.Find(id);
            db.OpenPositions.Remove(openPosition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        [Authorize(Roles ="Employee")]
        public ActionResult Apply(int id)
        {
            Application app = new Application();
            var appEmpId = User.Identity.GetUserId();
            var appUserDeets = (from a in db.UserDetails
                                where a.UserId == appEmpId
                                select a).First();

            app.OpenPositionId = id;
            app.UserId = User.Identity.GetUserId();
            app.ApplicationStatusId = 1;
            app.ResumeFilename = appUserDeets.ResumeFilename;
            app.ApplicationDate = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Applications.Add(app);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
    
}

FSWDFinalProject.UI.MVC/Views/OpenPositions/Create.cshtml
@model FSWDFinalProject.DATA.EF.OpenPosition

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OpenPosition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PositionId, "PositionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "LocationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSWDFinalProject.UI.MVC/Views/OpenPositions/Delete.cshtml
@model FSWDFinalProject.DATA.EF.OpenPosition

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OpenPosition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.StoreNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.StoreNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FSWDFinalProject.UI.MVC/Views/OpenPositions/Details.cshtml
@model FSWDFinalProject.DATA.EF.OpenPosition

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OpenPosition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.StoreNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.StoreNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.JobDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.JobDescription)
        </dd>
    </dl>
</div>
<p>
    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.OpenPositionId })
    }
    @Html.ActionLink("Back to List", "Index")
</p>

FSWDFinalProject.UI.MVC/Views/OpenPositions/Edit.cshtml
@model FSWDFinalProject.DATA.EF.OpenPosition

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OpenPosition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OpenPositionId)

        <div class="form-group">
            @Html.LabelFor(model => model.PositionId, "Position", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FSWDFinalProject.UI.MVC/Views/OpenPositions/Index.cshtml
@model IEnumerable<FSWDFinalProject.DATA.EF.OpenPosition>

@{
    ViewBag.Title = "Open Positions";
}

<h2>@ViewBag.Title</h2>

@if (User.IsInRole("Admin") || User.IsInRole("Manager"))
{
    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
    </p>
}
<table class="table data-table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location.StoreNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position.Title)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.StoreNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position.Title)
                </td>
                <td>
                    <a href="@Url.Action("Details", "OpenPositions", new { id = item.OpenPositionId })">
                        <i class="fa fa-info-circle action-icons" aria-hidden="true"></i>
                    </a>
                    @if (User.IsInRole("Employee"))
                    {
                        <a href="@Url.Action("Apply", "OpenPositions", new { id = item.OpenPositionId })">
                            <i class="fa fa-check action-icons" aria-hidden="true"></i>
                        </a>
                    }
                        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                        {
                            <a href="@Url.Action("Edit", "OpenPositions", new { id=item.OpenPositionId })">
                                <i class="fa fa-pencil-square-o action-icons" aria-hidden="true"></i>
                            </a>
                            <a href="@Url.Action("Delete", "OpenPositions", new { id = item.OpenPositionId })">
                                <i class="fa fa-trash-o action-icons" aria-hidden="true"></i>
                            </a>
                        }
                    </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script>
        $(document).ready(function () {
            $(".data-table").DataTable();
        })
    </script>
}